language: node_js
node_js:
- stable
install:
- npm install
script:
- npm run stylelint
- npm run build
cache:
  directories:
  - $HOME/.npm
git:
  depth: 5
notifications:
  slack:
    rooms:
      - secure: "EeRUHyAaNbIDZ7e8xafzck2yIE2vLjTbsRmlZVJWNwmXh+CChnoVRmAeM8blUC8cDesTBjAl2Vwq40texqTxXlMY7pwyNYaBhtxxCfc7X19LaG9PmuteHkQ96F4YSVXVYu4n/cFG7+tPnMDgMaYzfoO5gWECMv5K4EfAndBJGLP2X6ovJM2+O6Meph3FvPTwyNxvT61bhyHAOHJ3W6FRkhkpm4uF4bwY2NJWbKzPz3X24MWijQmijZAaZ84oX2Q2Nj8D3/CK5a6E6hJYvpfSfu14qpr4iCdJGN9pFTGMzzIuLgUCUUXbetBL41bkHqasTVSvbHf2KPynJZDzJEOKcmD8gnjI9AgCrDnpZ43ludEaCT/nED986Dh4IMhlYoj8oug0KMgzihfx5OzXLax1quMUWF7mPGxioEv9+TULqQnUF1g3p1JGfir4BSvdOHNHvWqitDXBZC5WAgdtnYOHgzAwk5cbhiM435O5UhXCOG/MjLM6gdx6IsakmeF0V1JCto581Yihy7/PoHbC4kWmI9o4CHpL+YGYX1O/qz6M/6roLuI5epPZ+FNUWvmGD/8GsG5d+5HNwlO7DJctRVeILRGXFD58UQGJ6Qic9mUfWD6tVlp0zQBgePIuvqgRlcBiTKTrV+wDr5HTQE91vlFO0cUEIVJLapVsN3I0LGw/vgw="
    on_success: change
    on_failure: always