language: node_js
before_install: 
  - nvm install $(cat .nvmrc)
  - nvm use
  - echo "//npm.pkg.github.com/:_authToken=$GITHUB_AUTH_TOKEN" > .npmrc
  - npm config --global set agepartnership:registry https://npm.pkg.github.com
  - cp .npmrc ~/
install:
  - travis_wait npm ci
script:
  - npm run stylelint
  - npm run build
cache:
  directories:
  - $HOME/.npm
git:
  depth: 5
notifications:
  slack:
    rooms:
      - secure: YGXhtNnksKVOueLx0y8Sh7Izk2iw9qhtyQMpZj1UP3074214Kp8WK866p3sxqDccoQo4S64uXs43IjTPZWp4d8ovcVR9Ci1bJD+ASw41dUPm/OU78C3E5KIaTYyfiJUAN0ZBBKFoZDIt8YtsPPm+0lj9z7zzYqwgZFv/sYuhxfocnpK12RBZ8aFQMaHaJISZWPCdjuAYa+hscUoMrm3CSmnsG7adClwXBuriQt9T0+n6rQyl7tPnwSj1AAW00ivWpjVZf9Yrc2GlXTl6144D+fpLbODZZowf2BlbuqaRb2jGBxCNVUAY6WL8WG3CLR05Utdi3UvIgFm10VJH9tCmzbnKcgsFcjAzW/NaAw9QuctGvwuSk9+9FPIH9ImdpfW8vAKC44Hu808tAkKHscWQgBt0KZDcBWhGfwqS3zCPk0yyq7w1ldGXlqnTKu5nvJAdxa7fRknN1/n47fFA1Y0AlWVg8ozgNH40g8pvco1rxdqmCieSYmqGyztsyzD1P1VPlBSyMAinlNZXft7y/4T9QOWKJXB3DFJe/OMGM14aejBk+SG5ivOMe0msw8RCRnm9i+7CjuEl57TiZ2CVc2zdmBqPPKByoA1k2QP8SL/kc79oQkXFIa9TUxyGoNVS0/VGE8aHOtYCSZXf4Sa2Cw9GuETrvun2IEguwcrOoVuMvIE=
    on_success: change
    on_failure: always
