language: node_js
node_js:
- stable
install:
- npm install
script:
- npm run stylelint
- npm run build
cache:
  directories:
  - $HOME/.npm
git:
  depth: 5
notifications:
  slack:
    rooms:
      - secure: GaoIpWbuXpmasQtWZSIsQU+QW2C0uGzxGc6PvoGgY4RA3rAXhSKo9Iweyf8tvohg7sApcclrw+53HtvSVjG5nBDdyiLENf4kwwwc7+vMI3wRHK7+t9Frburn4MM/lF45tsWbIbDxHF1AcW1jysjLarsjChlycUusxS466690vtwpro6KXEtDLqFtJ3AQgpWzT5G1o/A148Sl9OmraobRt/maKDH8oZ1u34v0UblGey7n3d4oSL+SdmZ66Jg4Vih54+XSNZz8ab4DrsxlNU3bL5gaMPDzd+Qf8AeFvh0mIBZOC7TX0+KNFzFZy7PB5EYn4OmLfAcsBtsal5Bjwn6rjngbOhl8q/F8ljLevyztKvLoWWTttGDZvKdijRGOiRj3kQZjTIPGwybFGAJbD/61P/K31sMxVXmwla9TGdRUU0UdFfKABg2tKUgU00P6CYaFEtaH/Wu0MlQlEn+8EU72xicc1OMKjNxrOtki2LoQYT2NNpsIq910YMunC6+nbtFGr1JCBNrsu7ntTzP4mQJZ4IpkcjTikgNnfkfPXzcr0YpnNT0nGzIzMuGYti/SVqt/dlK4beoOkw9h86hR5jlZQNh9MMtKroi5WVeAhiUBtnK+CzFDTavtE0cTOMjQ50Reka202Ro6mWEEhrVU5IFHBLbkuFY4plh4QgmbwRFRsls=
    on_success: change
    on_failure: always