language: node_js
node_js:
- stable
install:
- npm install
script:
- npm run stylelint
- npm run build
cache:
  directories:
  - $HOME/.npm
git:
  depth: 5
notifications:
  slack:
    rooms:
      - secure: bIoNknQmwzcPNXA5VPhU8tQY/FEgF/02m9dsB/AMIKtJOcx4wIVfsGvyl2ZL0yYCJZVC8j22mullvEHSusy2B8qHsI2glKazIaweRq1g+zZtIr4238hs23jQNOtSZRoQf0TQE9lHGCBfW99yAnJ3YgWgFn89haNFIGzYC6ZbeuTPAyvR6T6Z9aU1jNqbPZc7+dr2oRVdaoIKjO6Ub9oYhh579hE96Ori1pc67e9rUXzFVdwWe7tl8cqJZjNH6Z2Moi0Evnz2xmmIq0oiEtDNz/1QwNrI8K+nFB/fBIE+km33dhupeZkjP5uHfC2FBREtBNygqIZgPG1jVOIHQqtL0mhqRhFrZbjniUo8pJ21S7VlSX2RatEBCBA3ECBFJuNZBzu1iVi0BSUn9nejNlrqgR831jDlaGA8OoW7CDmCLJGwA4aFQtxHIkReXv8z1E7P6IAEh/7OLXRjrsyypi8wPmJddzjsG4nD2NftjhZb0WJwh+oZuQSzkAIJUAKPPAZv8PJX4fFR4l4BKtlfTSs0Hc7RTlAaokzoWVxxyHoNseTjJ0m/B8KvH72JDyJD3i77OZQF3zvirE+IDLR/ujlcs79hE/1T9K40SypkoKJ8wQ708jcw5U340q0JA7gBWESYXrpfTgnc3aHHlj5ghTmMdQtpgoZlImAic2KO8ojRT6E=
    on_success: change
    on_failure: always